seed: 7

dataset_name: RSNA_ICH_Dataset  # i.e. data/{dataset_name}/ contains train, eval and labels.csv
class_names : ['Hemo']

dataset: src.data_pipeline.DataLoader
model: src.model_building.AdjModel

data_pipeline:
  train_csv: 'C:/Users/Azin/PycharmProjects/one_class/hemo-expert/data/slices.pkl'
  validation_csv: 'C:/Users/Azin/PycharmProjects/one_class/hemo-expert/data/slices.pkl'
  class_name: data_pipeline.Dataset
  val_split: 0.2
  shuffle: true
  batch_size: 16
  label_map: {'non-hemo': 0, 'hemo': 1}
  train_batch_size : 10
  val_batch_size : 10
  image_dimension : 256

preprocessing:
  brain_window: [0, 80]
  subdural_window: [-20, 180]
  soft_window: [-150, 230]
  target_size: 256
  min_dcm_files_for_series: 15

trainer:
  export_metric: 'loss'
  export_mode: 'min'
  epochs: 1

exporter:
#  pyfunc_model: inference.MyHemoModel


model_builder:
  input_shape: [256, 256, 3]
  activation: 'relu'
  weights: null  # or 'imagenet'
  threshold: 0.5
  initial_learning_rate : 1e-3


evaluation:
  evaluation_csv: 'C:/Users/Azin/PycharmProjects/one_class/hemo-expert/data/slices.pkl'
  eval_batch_size: 10

artifacts:
  run_url: null
  model_url: null